"""Shared contracts for independently testable VerseVAD analysis modules."""

from versevad.core.documents import (
    DependencyRecord,
    DocumentWarning,
    DocumentWarningSeverity,
    EntityRecord,
    ModelVocabularyState,
    OrthographicFeatureKind,
    OrthographicSpan,
    PoemDocument,
    PreprocessingConfiguration,
    ProcessingCoverage,
    SentenceUnit,
    StructuralUnit,
    StructuralUnitKind,
    TokenClassification,
    TokenRole,
)
from versevad.core.modules import (
    AnalysisModule,
    ModuleCoverage,
    ModuleInput,
    ModuleMetric,
    ModuleProvenance,
    ModuleResult,
    ModuleWarning,
    ResultLayer,
    WarningSeverity,
)
from versevad.core.resources import (
    LocalResourceManager,
    ResourceProvenance,
    ResourceSpec,
    ResourceState,
    ResourceStatus,
)

__all__ = [
    "AnalysisModule",
    "DependencyRecord",
    "DocumentWarning",
    "DocumentWarningSeverity",
    "EntityRecord",
    "LocalResourceManager",
    "ModelVocabularyState",
    "ModuleCoverage",
    "ModuleInput",
    "ModuleMetric",
    "ModuleProvenance",
    "ModuleResult",
    "ModuleWarning",
    "OrthographicFeatureKind",
    "OrthographicSpan",
    "PoemDocument",
    "PreprocessingConfiguration",
    "ProcessingCoverage",
    "ResourceProvenance",
    "ResourceSpec",
    "ResourceState",
    "ResourceStatus",
    "ResultLayer",
    "SentenceUnit",
    "StructuralUnit",
    "StructuralUnitKind",
    "TokenClassification",
    "TokenRole",
    "WarningSeverity",
]
