"""Expanded, source-documented inherited-form profile catalog.

The registry intentionally distinguishes automatic, partial, and manual
assessment.  A manual profile remains inspectable with its requirements and
weights, but it can never become an automatic VerseVAD suggestion.
"""

from __future__ import annotations

from typing import Any, Callable


POETS_GLOSSARY = "https://poets.org/glossary"
POETRY_FOUNDATION_FORMS = (
    "https://www.poetryfoundation.org/education/glossary/fixed-and-unfixed-forms"
)
WRITERS_DIGEST_FORMS = (
    "https://www.writersdigest.com/write-better-poetry/"
    "list-of-50-poetic-forms-for-poets"
)


def build_expanded_form_profiles(
    *,
    form_profile: Callable[..., Any],
    role: Any,
    rule: Callable[..., Any],
) -> tuple[Any, ...]:
    """Build registry v2 without creating a circular import."""

    def fixed(
        profile_id: str,
        name: str,
        family: str,
        tradition: str,
        definition: str,
        *,
        source_urls: tuple[str, ...] = (POETS_GLOSSARY,),
        line_count: int | tuple[int, int] | None = None,
        stanza_patterns: tuple[tuple[int, ...], ...] = (),
        rhyme_schemes: tuple[str, ...] = (),
        syllables: tuple[int, ...] = (),
        repeating_syllables: tuple[int, ...] = (),
        syllable_range: tuple[int, int] | None = None,
        word_counts: tuple[int, ...] = (),
        meter: tuple[str, int] | None = None,
        extra_rules: tuple[Any, ...] = (),
        limitations: tuple[str, ...] = (),
        assessment_mode: str = "automatic",
    ) -> Any:
        rules: list[Any] = []
        if isinstance(line_count, int):
            rules.append(
                rule(
                    "lines",
                    "line_count_exact",
                    "Line count",
                    role.REQUIRED,
                    5,
                    f"{line_count} lines",
                    count=line_count,
                )
            )
        elif line_count is not None:
            minimum, maximum = line_count
            rules.append(
                rule(
                    "lines",
                    "line_count_range",
                    "Line-count range",
                    role.REQUIRED,
                    4,
                    f"{minimum}-{maximum} lines",
                    minimum=minimum,
                    maximum=maximum,
                )
            )
        if stanza_patterns:
            rules.append(
                rule(
                    "stanzas",
                    "stanza_pattern",
                    "Stanza architecture",
                    role.REQUIRED,
                    4,
                    " or ".join("/".join(map(str, item)) for item in stanza_patterns),
                    patterns=stanza_patterns,
                )
            )
        if rhyme_schemes:
            rules.append(
                rule(
                    "rhyme",
                    "rhyme_scheme",
                    "Rhyme architecture",
                    role.REQUIRED,
                    5,
                    " or ".join(rhyme_schemes),
                    schemes=rhyme_schemes,
                )
            )
        if syllables:
            rules.append(
                rule(
                    "syllables",
                    "syllable_pattern",
                    "Syllable pattern",
                    role.REQUIRED,
                    5,
                    "/".join(map(str, syllables)),
                    counts=syllables,
                )
            )
        if repeating_syllables:
            rules.append(
                rule(
                    "syllables",
                    "syllable_pattern_repeating",
                    "Repeating syllable pattern",
                    role.PREFERRED,
                    4,
                    "/".join(map(str, repeating_syllables)) + " repeating",
                    counts=repeating_syllables,
                )
            )
        if syllable_range is not None:
            minimum, maximum = syllable_range
            rules.append(
                rule(
                    "syllable_range",
                    "syllable_range",
                    "Line syllable range",
                    role.PREFERRED,
                    3,
                    f"{minimum}-{maximum} syllables per line",
                    minimum=minimum,
                    maximum=maximum,
                )
            )
        if word_counts:
            rules.append(
                rule(
                    "word_counts",
                    "word_count_pattern",
                    "Words per line",
                    role.REQUIRED,
                    5,
                    "/".join(map(str, word_counts)),
                    counts=word_counts,
                )
            )
        if meter is not None:
            pattern, foot_count = meter
            rules.append(
                rule(
                    "meter",
                    "meter_pattern",
                    "Governing meter",
                    role.PREFERRED,
                    4,
                    f"{pattern} meter with {foot_count} feet",
                    pattern=pattern,
                    foot_count=foot_count,
                )
            )
        rules.extend(extra_rules)
        tooltip = f"Traditionally: {definition[0].lower() + definition[1:]}"
        return form_profile(
            profile_id=profile_id,
            name=name,
            family=family,
            tradition=tradition,
            definition=definition,
            tooltip_definition=tooltip,
            rules=tuple(rules),
            source_urls=source_urls,
            limitations=limitations,
            assessment_mode=assessment_mode,
        )

    def manual(
        profile_id: str,
        name: str,
        family: str,
        tradition: str,
        definition: str,
        *,
        source_urls: tuple[str, ...] = (POETS_GLOSSARY,),
        expected: str | None = None,
        limitations: tuple[str, ...] = (),
        observable_rules: tuple[Any, ...] = (),
    ) -> Any:
        requirements = (
            *observable_rules,
            rule(
                "scholarly_confirmation",
                "manual_requirement",
                "Contextual or compositional requirement",
                role.REQUIRED,
                5,
                expected or definition,
            ),
        )
        return form_profile(
            profile_id=profile_id,
            name=name,
            family=family,
            tradition=tradition,
            definition=definition,
            tooltip_definition=(
                f"Traditionally: {definition[0].lower() + definition[1:]} "
                "VerseVAD preserves this profile for manual checking because "
                "the defining evidence is not recoverable safely from structure alone."
            ),
            rules=requirements,
            source_urls=source_urls,
            limitations=(
                *limitations,
                "This profile cannot become an automatic suggestion without scholar-supplied contextual evidence.",
            ),
            assessment_mode="manual",
        )

    poets = "https://poets.org/glossary/"
    foundation = "https://www.poetryfoundation.org/education/glossary/"
    wd = "https://www.writersdigest.com/write-better-poetry/"

    automatic = (
        fixed(
            "abecedarian",
            "Abecedarian",
            "alphabetic form",
            "Cross-cultural alphabetic and devotional traditions",
            "A poem whose successive lines or stanzas proceed through an alphabetic sequence.",
            extra_rules=(
                rule(
                    "alphabet",
                    "alphabetic_line_initials",
                    "Alphabetic initials",
                    role.REQUIRED,
                    8,
                    "Successive line initials follow A, B, C, and onward",
                ),
            ),
            source_urls=(poets + "abecedarian",),
            limitations=("Stanza-initial and non-Latin alphabet variants require manual review.",),
        ),
        fixed(
            "ballad_stanza",
            "Traditional Ballad Stanza",
            "narrative stanza form",
            "English and Scottish oral-ballad traditions",
            "Quatrains usually rhyming ABCB and alternating four-stress with three-stress lines.",
            rhyme_schemes=("ABCB",),
            extra_rules=(
                rule(
                    "stanza_sequence",
                    "uniform_stanza_size",
                    "Quatrain sequence",
                    role.PREFERRED,
                    3,
                    "Four-line stanzas throughout",
                    size=4,
                    minimum=1,
                ),
                rule(
                    "stress",
                    "stress_count_pattern_repeating",
                    "Alternating stress count",
                    role.PREFERRED,
                    3,
                    "Approximately four/three/four/three stresses",
                    counts=(4, 3, 4, 3),
                ),
            ),
            source_urls=(foundation + "ballad",),
            limitations=("Narrative transmission, tune, and oral provenance are not inferred.",),
        ),
        fixed(
            "ballade",
            "Ballade",
            "French fixed form",
            "Medieval French and later English traditions",
            "Three eight-line stanzas and a four-line envoi, using repeated rhymes and the same refrain line.",
            line_count=28,
            stanza_patterns=((8, 8, 8, 4),),
            rhyme_schemes=("ABABBCBCABABBCBCABABBCBCBCBC",),
            extra_rules=(
                rule(
                    "refrain",
                    "stanza_refrain",
                    "Closing refrain",
                    role.REQUIRED,
                    6,
                    "Every stanza and the envoi end with the same line",
                ),
            ),
            source_urls=(poets + "ballade",),
        ),
        fixed(
            "blank_verse",
            "Blank Verse",
            "metrical verse",
            "English dramatic and narrative traditions",
            "Unrhymed verse written predominantly in iambic pentameter.",
            line_count=(2, 100000),
            meter=("iambic", 5),
            extra_rules=(
                rule(
                    "unrhymed",
                    "rhyme_absence",
                    "Absence of systematic end rhyme",
                    role.REQUIRED,
                    5,
                    "Little or no robust end-rhyme grouping",
                    maximum_density=0.20,
                ),
            ),
            source_urls=(foundation + "blank-verse",),
            limitations=("VerseVAD does not infer dramatic or epic function.",),
        ),
        fixed(
            "blues_stanza",
            "Blues Stanza Profile",
            "repeating-line stanza form",
            "African American oral and musical traditions",
            "A three-line blues stanza in which line two repeats or varies line one and line three answers or turns it.",
            line_count=(3, 300),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Tercet sequence",
                    role.PREFERRED,
                    3,
                    "Three-line stanzas",
                    size=3,
                    minimum=1,
                ),
                rule(
                    "aab",
                    "blues_repetition",
                    "AAB repetition",
                    role.REQUIRED,
                    7,
                    "The first two lines of each tercet repeat or closely echo",
                ),
            ),
            source_urls=(poets + "blues-poem",),
            limitations=("Musical phrasing, African American performance tradition, and thematic response require contextual reading.",),
            assessment_mode="partial",
        ),
        fixed(
            "bop",
            "Bop",
            "contemporary refrain form",
            "African American / Cave Canem tradition",
            "Three argument stanzas of six, eight, and six lines, each followed by the same refrain.",
            line_count=23,
            stanza_patterns=((7, 9, 7), (6, 1, 8, 1, 6, 1)),
            extra_rules=(
                rule(
                    "refrain",
                    "bop_refrain",
                    "Repeated refrain",
                    role.REQUIRED,
                    7,
                    "The same refrain follows the 6-, 8-, and 6-line sections",
                ),
            ),
            source_urls=(poets + "bop",),
            limitations=("Problem, exploration, and resolution functions are not inferred.",),
        ),
        fixed(
            "crapsey_cinquain",
            "Crapsey Cinquain",
            "syllabic short form",
            "Early twentieth-century American",
            "A five-line cinquain commonly adapted as a 2/4/6/8/2 syllable pattern.",
            line_count=5,
            syllables=(2, 4, 6, 8, 2),
            source_urls=(poets + "cinquain", wd + "cinquain-poetic-forms"),
            limitations=("Crapsey described an accentual 1/2/3/4/1 pattern; the syllabic classroom adaptation is modeled explicitly here.",),
        ),
        fixed(
            "clerihew",
            "Clerihew",
            "comic quatrain",
            "English light verse",
            "A four-line biographical comic poem made of two irregular rhyming couplets, AABB.",
            line_count=4,
            rhyme_schemes=("AABB",),
            extra_rules=(
                rule(
                    "irregularity",
                    "line_length_variation",
                    "Deliberately unequal line lengths",
                    role.PREFERRED,
                    2,
                    "Noticeably unequal line lengths",
                    minimum_cv=0.12,
                ),
            ),
            source_urls=(poets + "Clerihew",),
            limitations=("Biographical subject and comic deadpan are not scored.",),
            assessment_mode="partial",
        ),
        fixed(
            "doha",
            "Doha",
            "rhyming couplet form",
            "Hindi and Urdu traditions",
            "A self-contained rhyming couplet whose two lines each contain twenty-four syllables, conventionally divided 13/11 internally.",
            line_count=2,
            rhyme_schemes=("AA",),
            syllables=(24, 24),
            source_urls=(poets + "doha",),
            limitations=("Internal mātrā groupings and proverbial or devotional function require manual review.",),
            assessment_mode="partial",
        ),
        fixed(
            "duplex",
            "Duplex",
            "contemporary echo form",
            "Contemporary African American",
            "Fourteen lines in seven couplets, nine to eleven syllables per line, with linked echoes and a final return to the opening.",
            line_count=14,
            stanza_patterns=((2, 2, 2, 2, 2, 2, 2), (14,)),
            syllable_range=(9, 11),
            extra_rules=(
                rule(
                    "echo",
                    "duplex_echo",
                    "Couplet-to-couplet echo",
                    role.REQUIRED,
                    7,
                    "Each couplet's second line is echoed by the next couplet's first",
                ),
                rule(
                    "closure",
                    "first_last_line_echo",
                    "Circular closure",
                    role.REQUIRED,
                    4,
                    "The final line echoes the opening line",
                ),
            ),
            source_urls=(poets + "duplex",),
            limitations=("Semantic surprise and the form's ghazal/blues/sonnet dialogue are not scored.",),
        ),
        fixed(
            "glosa",
            "Glosa / Glose",
            "quotation-and-refrain form",
            "Spanish and European traditions",
            "A quatrain epigraph followed by four ten-line stanzas whose last lines repeat the epigraph lines in order.",
            line_count=44,
            stanza_patterns=((4, 10, 10, 10, 10),),
            extra_rules=(
                rule(
                    "refrains",
                    "glosa_refrains",
                    "Epigraph-line refrains",
                    role.REQUIRED,
                    8,
                    "Lines 14, 24, 34, and 44 repeat epigraph lines 1-4",
                ),
            ),
            source_urls=(poets + "glosa",),
            limitations=("Authorship and provenance of the opening quotation require manual confirmation.",),
        ),
        fixed(
            "hudibrastic_verse",
            "Hudibrastic Verse",
            "comic couplet verse",
            "English mock-heroic tradition",
            "Narrative comic verse in eight-syllable lines arranged as rhyming couplets.",
            line_count=(2, 100000),
            repeating_syllables=(8,),
            extra_rules=(
                rule(
                    "couplets",
                    "rhyme_couplets",
                    "Rhyming couplets",
                    role.REQUIRED,
                    5,
                    "AA BB CC and onward",
                ),
            ),
            source_urls=(poets + "hudibrastic-verse",),
            limitations=("Comic narrative and deliberately grotesque rhymes are not inferred.",),
            assessment_mode="partial",
        ),
        fixed(
            "madrigal_profile",
            "Madrigal Profile",
            "short lyric/song form",
            "Italian and English musical traditions",
            "A five- to fourteen-line lyric, often seven to eleven syllables per line, conventionally closing with a rhyming couplet.",
            line_count=(5, 14),
            syllable_range=(7, 11),
            extra_rules=(
                rule(
                    "couplet",
                    "terminal_rhyming_couplet",
                    "Closing couplet",
                    role.PREFERRED,
                    4,
                    "The final two lines rhyme",
                ),
            ),
            source_urls=(poets + "madrigal", foundation + "madrigal"),
            limitations=("Polyphonic musical setting and lyric function are not inferable from text alone.",),
            assessment_mode="partial",
        ),
        fixed(
            "monostich",
            "Monostich",
            "single-line form",
            "Cross-cultural",
            "A poem consisting of one line.",
            line_count=1,
            source_urls=(poets + "monostich",),
            assessment_mode="partial",
            limitations=("A single imported prose sentence may be structurally indistinguishable.",),
        ),
        fixed(
            "ottava_rima",
            "Ottava Rima",
            "Italian stanza form",
            "Italian and English narrative traditions",
            "Eight-line stanzas rhyming ABABABCC, traditionally hendecasyllabic in Italian and often iambic pentameter in English.",
            line_count=(8, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Octave sequence",
                    role.REQUIRED,
                    4,
                    "Eight-line stanzas",
                    size=8,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Repeating rhyme scheme",
                    role.REQUIRED,
                    6,
                    "ABABABCC in every stanza",
                    scheme="ABABABCC",
                ),
            ),
            meter=("iambic", 5),
            source_urls=(foundation + "ottava-rima",),
        ),
        fixed(
            "rhyme_royal",
            "Rhyme Royal",
            "seven-line stanza form",
            "English Chaucerian tradition",
            "Seven-line stanzas, usually iambic pentameter, rhyming ABABBCC.",
            line_count=(7, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Seven-line stanza sequence",
                    role.REQUIRED,
                    4,
                    "Seven-line stanzas",
                    size=7,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Repeating rhyme scheme",
                    role.REQUIRED,
                    6,
                    "ABABBCC in every stanza",
                    scheme="ABABBCC",
                ),
            ),
            meter=("iambic", 5),
            source_urls=(POETRY_FOUNDATION_FORMS,),
        ),
        fixed(
            "spenserian_stanza",
            "Spenserian Stanza",
            "nine-line stanza form",
            "English Renaissance",
            "Nine-line stanzas rhyming ABABBCBCC: eight iambic-pentameter lines followed by an alexandrine.",
            line_count=(9, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Nine-line stanza sequence",
                    role.REQUIRED,
                    4,
                    "Nine-line stanzas",
                    size=9,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Repeating rhyme scheme",
                    role.REQUIRED,
                    6,
                    "ABABBCBCC in every stanza",
                    scheme="ABABBCBCC",
                ),
                rule(
                    "alexandrine",
                    "terminal_line_longer",
                    "Alexandrine close",
                    role.PREFERRED,
                    3,
                    "Every ninth line is longer than the preceding eight",
                    period=9,
                ),
            ),
            meter=("iambic", 5),
            source_urls=(foundation + "spenserian-stanza",),
        ),
        fixed(
            "heroic_couplets",
            "Heroic Couplets",
            "rhyming couplet verse",
            "English neoclassical and narrative traditions",
            "Successive rhyming couplets written predominantly in iambic pentameter.",
            line_count=(2, 100000),
            meter=("iambic", 5),
            extra_rules=(
                rule(
                    "couplets",
                    "rhyme_couplets",
                    "Successive rhyming couplets",
                    role.REQUIRED,
                    6,
                    "AA BB CC and onward",
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
        ),
        fixed(
            "burns_stanza",
            "Burns Stanza / Standard Habbie",
            "six-line stanza form",
            "Scots and English traditions",
            "Six-line stanzas rhyming AAABAB, with longer lines 1/2/3/5 and shorter lines 4/6.",
            line_count=(6, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Six-line stanza sequence",
                    role.REQUIRED,
                    4,
                    "Six-line stanzas",
                    size=6,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Repeating rhyme scheme",
                    role.REQUIRED,
                    5,
                    "AAABAB in every stanza",
                    scheme="AAABAB",
                ),
                rule(
                    "length",
                    "periodic_line_length_relation",
                    "Long/short line pattern",
                    role.PREFERRED,
                    3,
                    "Lines 4 and 6 shorter in every stanza",
                    period=6,
                    long_positions=(1, 2, 3, 5),
                    short_positions=(4, 6),
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "venus_and_adonis_stanza",
            "Venus and Adonis Stanza",
            "six-line stanza form",
            "English Renaissance",
            "Six iambic-pentameter lines rhyming ABABCC.",
            line_count=(6, 100000),
            meter=("iambic", 5),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Six-line stanza sequence",
                    role.REQUIRED,
                    4,
                    "Six-line stanzas",
                    size=6,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Repeating rhyme scheme",
                    role.REQUIRED,
                    6,
                    "ABABCC in every stanza",
                    scheme="ABABCC",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "tail_rhyme_stanza",
            "Tail-Rhyme Stanza",
            "stanzaic rhyme form",
            "Medieval and later English",
            "A stanza with longer lines interrupted or closed by shorter tail lines, commonly AABCCB.",
            line_count=(6, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Six-line stanza sequence",
                    role.PREFERRED,
                    3,
                    "Six-line stanzas",
                    size=6,
                    minimum=1,
                ),
                rule(
                    "rhyme",
                    "rhyme_scheme_repeating",
                    "Tail-rhyme pattern",
                    role.REQUIRED,
                    5,
                    "AABCCB in every stanza",
                    scheme="AABCCB",
                ),
                rule(
                    "length",
                    "periodic_line_length_relation",
                    "Short tail lines",
                    role.PREFERRED,
                    3,
                    "Lines 3 and 6 shorter than surrounding lines",
                    period=6,
                    long_positions=(1, 2, 4, 5),
                    short_positions=(3, 6),
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "renga",
            "Renga Structural Profile",
            "linked collaborative form",
            "Japanese",
            "Alternating three-line 5/7/5 and two-line 7/7 stanzas in a collaboratively linked sequence.",
            line_count=(5, 100000),
            repeating_syllables=(5, 7, 5, 7, 7),
            extra_rules=(
                rule(
                    "stanzas",
                    "alternating_stanza_sizes",
                    "Alternating tercets and couplets",
                    role.REQUIRED,
                    5,
                    "3/2 stanza sizes repeating",
                    sizes=(3, 2),
                ),
            ),
            source_urls=(poets + "renga",),
            limitations=("Collaboration, seasonal vocabulary, and semantic linking cannot be inferred.",),
            assessment_mode="partial",
        ),
        fixed(
            "kasen_renga",
            "Kasen Renga Structural Profile",
            "linked collaborative form",
            "Japanese",
            "A favored thirty-six-link renga sequence alternating three-line and two-line stanzas.",
            line_count=36,
            repeating_syllables=(5, 7, 5, 7, 7),
            extra_rules=(
                rule(
                    "stanzas",
                    "alternating_stanza_sizes",
                    "Alternating tercets and couplets",
                    role.REQUIRED,
                    5,
                    "3/2 stanza sizes repeating",
                    sizes=(3, 2),
                ),
            ),
            source_urls=(poets + "renga",),
            limitations=("Traditional seasonal, lunar, floral, collaborative, and link/shift rules require specialist review.",),
            assessment_mode="partial",
        ),
        fixed(
            "tanka",
            "Tanka Structural Profile",
            "Japanese short form",
            "Japanese waka tradition",
            "A thirty-one-syllable poem conventionally presented in English as five lines of 5/7/5/7/7.",
            line_count=5,
            syllables=(5, 7, 5, 7, 7),
            source_urls=(poets + "tanka", foundation + "tanka"),
            limitations=("Japanese morae, the pivotal image, and the poem's historical single-line presentation are not scored.",),
        ),
        fixed(
            "sijo",
            "Sijo Structural Profile",
            "Korean song form",
            "Korean",
            "A three-line poem of approximately fourteen to sixteen syllables per line and forty-four to forty-six syllables overall.",
            line_count=3,
            syllable_range=(14, 16),
            extra_rules=(
                rule(
                    "total",
                    "total_syllable_range",
                    "Total syllable range",
                    role.REQUIRED,
                    5,
                    "44-46 syllables overall",
                    minimum=44,
                    maximum=46,
                ),
            ),
            source_urls=(foundation + "sijo",),
            limitations=("Internal phrase divisions and the thematic turn/closure require manual reading; six-line modern layouts may not score fully.",),
            assessment_mode="partial",
        ),
        fixed(
            "landay",
            "Landay",
            "oral couplet form",
            "Pashtun / Afghan folk tradition",
            "An orally performed twenty-two-syllable couplet with nine syllables in the first line and thirteen in the second.",
            line_count=2,
            syllables=(9, 13),
            source_urls=(foundation + "landays",),
            limitations=("The conventional final ma/na sound, anonymity, performance, and cultural function require specialist review.",),
            assessment_mode="partial",
        ),
        fixed(
            "sedoka",
            "Sedōka Structural Profile",
            "Japanese short form",
            "Classical Japanese",
            "Two katauta units arranged as six lines of 5/7/7/5/7/7.",
            line_count=6,
            syllables=(5, 7, 7, 5, 7, 7),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("English syllables are only an approximation of Japanese sound units.",),
        ),
        fixed(
            "choka",
            "Chōka Structural Profile",
            "Japanese long form",
            "Classical Japanese",
            "A long poem alternating 5- and 7-sound units and closing with an additional 7-unit segment.",
            line_count=(3, 100000),
            extra_rules=(
                rule(
                    "alternation",
                    "choka_syllable_pattern",
                    "Alternating 5/7 close",
                    role.REQUIRED,
                    7,
                    "5/7 pairs followed by a final 7",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("English syllables approximate Japanese on; envoy and thematic conventions are not assessed.",),
            assessment_mode="partial",
        ),
        fixed(
            "katauta",
            "Katauta Structural Profile",
            "Japanese short form",
            "Classical Japanese",
            "A three-line half-poem commonly represented as 5/7/7 sound units.",
            line_count=3,
            syllables=(5, 7, 7),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("English syllables approximate Japanese on.",),
        ),
        fixed(
            "somonka",
            "Somonka Structural Profile",
            "paired Japanese short form",
            "Classical Japanese",
            "An exchange of two tanka, represented as two 5/7/5/7/7 units.",
            line_count=10,
            stanza_patterns=((5, 5), (10,)),
            syllables=(5, 7, 5, 7, 7, 5, 7, 5, 7, 7),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("The dialogic exchange and Japanese sound units require manual confirmation.",),
            assessment_mode="partial",
        ),
        fixed(
            "rondeau",
            "Rondeau",
            "French fixed refrain form",
            "French and English",
            "Fifteen lines in 5/4/6 stanzas, guided by two rhymes and a rentrement after lines 9 and 15.",
            line_count=15,
            stanza_patterns=((5, 4, 6),),
            syllable_range=(8, 10),
            extra_rules=(
                rule(
                    "rhyme",
                    "rhyme_scheme",
                    "Two-rhyme architecture",
                    role.REQUIRED,
                    5,
                    "AABBA AABR AABBAR",
                    schemes=("AABBAAABXAABBAX",),
                ),
                rule(
                    "refrain",
                    "partial_refrain_positions",
                    "Rentrement",
                    role.REQUIRED,
                    6,
                    "Opening words recur at lines 9 and 15",
                    anchor=1,
                    positions=(9, 15),
                ),
            ),
            source_urls=(poets + "rondeau",),
        ),
        fixed(
            "triolet",
            "Triolet",
            "French fixed refrain form",
            "French and English",
            "An eight-line, two-rhyme form ABaAabAB in which lines 1 and 2 recur at prescribed positions.",
            line_count=8,
            rhyme_schemes=("ABAAABAB",),
            extra_rules=(
                rule(
                    "refrains",
                    "line_repetition_groups",
                    "Repeated lines",
                    role.REQUIRED,
                    7,
                    "Line 1 repeats at 4 and 7; line 2 repeats at 8",
                    groups=((1, 4, 7), (2, 8)),
                ),
            ),
            source_urls=(poets + "triolet",),
        ),
        fixed(
            "rondelet",
            "Rondelet",
            "French fixed refrain form",
            "French and English",
            "A seven-line form using two rhymes, with the opening refrain returning as lines 3 and 7.",
            line_count=7,
            rhyme_schemes=("ABARABB",),
            extra_rules=(
                rule(
                    "refrain",
                    "line_repetition_groups",
                    "Opening refrain",
                    role.REQUIRED,
                    7,
                    "Line 1 repeats at lines 3 and 7",
                    groups=((1, 3, 7),),
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "rondel",
            "Rondel",
            "French fixed refrain form",
            "French and English",
            "A thirteen- or fourteen-line two-rhyme form whose opening two lines return as refrains.",
            line_count=(13, 14),
            extra_rules=(
                rule(
                    "refrains",
                    "rondel_refrains",
                    "Opening-line refrains",
                    role.REQUIRED,
                    7,
                    "Opening lines recur after the second quatrain and at the close",
                ),
                rule(
                    "two_rhymes",
                    "rhyme_class_count",
                    "Two-rhyme constraint",
                    role.PREFERRED,
                    4,
                    "Two principal end-rhyme families",
                    count=2,
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
        ),
        fixed(
            "chant_royal",
            "Chant Royal",
            "French fixed refrain form",
            "Medieval French",
            "Five eleven-line stanzas and a five-line envoi, using five rhymes and one repeated refrain.",
            line_count=60,
            stanza_patterns=((11, 11, 11, 11, 11, 5),),
            extra_rules=(
                rule(
                    "refrain",
                    "stanza_refrain",
                    "Closing refrain",
                    role.REQUIRED,
                    6,
                    "Every stanza and the envoi end with the same line",
                ),
            ),
            source_urls=(wd + "longer-poetic-forms",),
        ),
        fixed(
            "dizain",
            "Dizain",
            "French stanza form",
            "French and English",
            "A ten-line stanza, conventionally of ten syllables per line, often rhyming ABABBCCDCD.",
            line_count=10,
            rhyme_schemes=("ABABBCCDCD",),
            syllables=(10, 10, 10, 10, 10, 10, 10, 10, 10, 10),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "decima_espinela",
            "Décima Espinela",
            "Spanish stanza form",
            "Spanish-language and Latin American",
            "A ten-line octosyllabic stanza rhyming ABBAACCDDC.",
            line_count=10,
            rhyme_schemes=("ABBAACCDDC",),
            syllables=(8, 8, 8, 8, 8, 8, 8, 8, 8, 8),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Spanish syllabification and synaloepha differ from English dictionary syllable counts.",),
        ),
        fixed(
            "redondilla",
            "Redondilla",
            "Spanish quatrain form",
            "Spanish-language",
            "An octosyllabic quatrain conventionally rhyming ABBA.",
            line_count=4,
            rhyme_schemes=("ABBA",),
            syllables=(8, 8, 8, 8),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Spanish prosody is approximated by English-oriented pronunciation evidence.",),
        ),
        fixed(
            "romance",
            "Romance / Spanish Ballad Profile",
            "Spanish narrative verse",
            "Spanish-language",
            "A sequence of octosyllabic lines with assonance on even lines and unrhymed odd lines.",
            line_count=(4, 100000),
            repeating_syllables=(8,),
            extra_rules=(
                rule(
                    "even_assonance",
                    "even_line_assonance",
                    "Even-line assonance",
                    role.REQUIRED,
                    5,
                    "Even-numbered lines share assonance; odd lines remain free",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("VerseVAD's English-oriented vowel model only approximates Spanish assonance.",),
            assessment_mode="partial",
        ),
        fixed(
            "seguidilla",
            "Seguidilla",
            "Spanish song stanza",
            "Spanish-language",
            "A seven-line stanza with 7/5/7/5/5/7/5 syllables and paired assonance on lines 2/4 and 5/7.",
            line_count=7,
            syllables=(7, 5, 7, 5, 5, 7, 5),
            extra_rules=(
                rule(
                    "assonance",
                    "seguidilla_assonance",
                    "Assonance pairs",
                    role.PREFERRED,
                    4,
                    "Lines 2/4 and 5/7 share assonance",
                ),
            ),
            source_urls=(wd + "seguidilla-poetic-form",),
            assessment_mode="partial",
        ),
        fixed(
            "rubai",
            "Rubāʿī / Rubai",
            "quatrain form",
            "Persian",
            "A self-contained quatrain conventionally rhyming AABA or AAAA.",
            line_count=4,
            rhyme_schemes=("AABA", "AAAA"),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Quantitative meter and Persian prosody are not modeled.",),
            assessment_mode="partial",
        ),
        fixed(
            "rubaiyat_sequence",
            "Rubāʿiyāt Sequence",
            "linked quatrain sequence",
            "Persian-derived English tradition",
            "A sequence of rubai quatrains, often linked as AABA BBCB CCDC and onward in English adaptations.",
            line_count=(8, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Quatrain sequence",
                    role.REQUIRED,
                    3,
                    "Four-line stanzas",
                    size=4,
                    minimum=2,
                ),
                rule(
                    "chain",
                    "rubaiyat_chain",
                    "Linked AABA rhyme chain",
                    role.REQUIRED,
                    6,
                    "AABA BBCB CCDC and onward",
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Many rubāʿiyāt are collections rather than formally chained sequences.",),
            assessment_mode="partial",
        ),
        fixed(
            "masnavi",
            "Masnavi / Mathnawi Structural Profile",
            "rhyming couplet narrative",
            "Persian, Urdu, Turkish, and related traditions",
            "An extended poem in independently rhyming couplets, AA BB CC and onward, conventionally sharing one meter.",
            line_count=(4, 100000),
            extra_rules=(
                rule(
                    "couplets",
                    "rhyme_couplets",
                    "Independent rhyming couplets",
                    role.REQUIRED,
                    7,
                    "AA BB CC and onward",
                ),
                rule(
                    "length",
                    "line_length_uniformity",
                    "Line-length regularity",
                    role.PREFERRED,
                    2,
                    "Broadly consistent line length",
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Quantitative meter, language-specific rhyme, and narrative function require specialist review.",),
            assessment_mode="partial",
        ),
        fixed(
            "qasida",
            "Qasida / Qaṣīda Structural Profile",
            "monorhyme ode",
            "Arabic and Persianate traditions",
            "A long formal ode conventionally maintaining one meter and one end rhyme throughout.",
            line_count=(7, 100000),
            extra_rules=(
                rule(
                    "monorhyme",
                    "monorhyme",
                    "Single end-rhyme family",
                    role.REQUIRED,
                    7,
                    "One rhyme throughout",
                ),
                rule(
                    "length",
                    "line_length_uniformity",
                    "Line-length regularity",
                    role.PREFERRED,
                    2,
                    "Broadly consistent line length",
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Classical quantitative meter, bipartite lines, language, praise/satire purpose, and thematic sections are not inferred.",),
            assessment_mode="partial",
        ),
        fixed(
            "kyrielle",
            "Kyrielle",
            "French refrain form",
            "Medieval French and English devotional traditions",
            "A sequence of rhymed quatrains, often eight syllables per line, each ending in the same refrain.",
            line_count=(4, 100000),
            repeating_syllables=(8,),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Quatrain sequence",
                    role.REQUIRED,
                    3,
                    "Four-line stanzas",
                    size=4,
                    minimum=1,
                ),
                rule(
                    "refrain",
                    "stanza_refrain",
                    "Stanza-ending refrain",
                    role.REQUIRED,
                    6,
                    "Every stanza ends with the same line",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "terzanelle",
            "Terzanelle",
            "hybrid refrain form",
            "Modern English-language",
            "A nineteen-line hybrid of terza rima and villanelle, using interlocking rhyme and prescribed repeated lines.",
            line_count=19,
            stanza_patterns=((3, 3, 3, 3, 3, 4),),
            extra_rules=(
                rule(
                    "refrains",
                    "terzanelle_refrains",
                    "Terzanelle repeated lines",
                    role.REQUIRED,
                    6,
                    "Second and third lines recur at prescribed later positions",
                ),
                rule(
                    "rhyme",
                    "terza_rhyme",
                    "Interlocking terza-rima rhyme",
                    role.PREFERRED,
                    5,
                    "ABA BCB CDC and onward",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "onegin_stanza",
            "Onegin / Pushkin Stanza",
            "sonnet-length stanza",
            "Russian and translated traditions",
            "Fourteen lines of iambic tetrameter rhyming ABAB CCDD EFFE GG.",
            line_count=14,
            rhyme_schemes=("ABABCCDDEFFEGG",),
            meter=("iambic", 4),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Alternating masculine and feminine rhymes in Russian are not scored as a required distinction.",),
        ),
        fixed(
            "curtal_sonnet",
            "Curtal Sonnet Profile",
            "sonnet variant",
            "Gerard Manley Hopkins / English",
            "Hopkins's shortened proportional sonnet: about ten and a half printed lines, rhyming ABCABC DBCDC, with a shortened final tail.",
            line_count=11,
            rhyme_schemes=("ABCABCDBCDC",),
            extra_rules=(
                rule(
                    "tail",
                    "terminal_line_shorter",
                    "Shortened final line",
                    role.PREFERRED,
                    3,
                    "The final printed line is markedly shorter",
                ),
            ),
            source_urls=(foundation + "sonnet",),
            limitations=("The half-line convention and sprung rhythm require close scansion.",),
            assessment_mode="partial",
        ),
        fixed(
            "sonnet_redouble",
            "Sonnet Redoublé / Crown of Sonnets",
            "linked sonnet sequence",
            "European and English-language",
            "Fifteen linked sonnets: each final line becomes the next opening line, and the fifteenth sonnet gathers the fourteen linking lines.",
            line_count=210,
            extra_rules=(
                rule(
                    "links",
                    "sonnet_crown_links",
                    "Inter-sonnet line links",
                    role.REQUIRED,
                    8,
                    "Fourteen sonnet links plus a master sonnet",
                    sonnet_count=15,
                ),
            ),
            source_urls=(foundation + "sonnet",),
            limitations=("Some writers use 'crown' for shorter linked-sonnet sequences; this profile encodes the sonnet redoublé.",),
        ),
        fixed(
            "stretched_sonnet",
            "Stretched Sonnet Profile",
            "sonnet variant",
            "Modern English-language",
            "A sonnet-derived poem extended beyond fourteen lines, typically sixteen or more.",
            line_count=(16, 30),
            extra_rules=(
                rule(
                    "sonnet_metre",
                    "meter_pattern",
                    "Common sonnet meter",
                    role.OPTIONAL,
                    2,
                    "Often iambic pentameter",
                    pattern="iambic",
                    foot_count=5,
                ),
            ),
            source_urls=(foundation + "sonnet",),
            limitations=("Line count alone cannot establish sonnet derivation; manual confirmation remains important.",),
            assessment_mode="manual",
        ),
        fixed(
            "sapphic_stanza",
            "Sapphic Stanza Structural Profile",
            "classical stanza form",
            "Ancient Greek, Latin, and later accentual adaptations",
            "Four-line stanzas of three longer Sapphic lines followed by a short Adonic line, often approximated as 11/11/11/5 syllables.",
            line_count=(4, 100000),
            repeating_syllables=(11, 11, 11, 5),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Four-line stanza sequence",
                    role.REQUIRED,
                    3,
                    "Four-line stanzas",
                    size=4,
                    minimum=1,
                ),
            ),
            source_urls=(poets + "sapphic",),
            limitations=("Classical quantitative feet and language-specific adaptations are not recoverable from English lexical stress alone.",),
            assessment_mode="partial",
        ),
        fixed(
            "alcaic_stanza",
            "Alcaic Stanza Structural Profile",
            "classical stanza form",
            "Ancient Greek, Latin, and later accentual adaptations",
            "A four-line Alcaic stanza conventionally comprising two eleven-syllable lines, one nine-syllable line, and one ten-syllable line.",
            line_count=(4, 100000),
            repeating_syllables=(11, 11, 9, 10),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Four-line stanza sequence",
                    role.REQUIRED,
                    3,
                    "Four-line stanzas",
                    size=4,
                    minimum=1,
                ),
            ),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("Classical quantitative meter and accentual-language variants require specialist scansion.",),
            assessment_mode="partial",
        ),
        fixed(
            "shloka_anustubh",
            "Śloka / Anuṣṭubh Structural Profile",
            "classical syllabic verse",
            "Sanskrit",
            "A verse of four eight-syllable pādas, commonly printed as four short lines or two sixteen-syllable lines.",
            line_count=(2, 4),
            extra_rules=(
                rule(
                    "layout",
                    "syllable_pattern_alternatives",
                    "Pāda layout",
                    role.REQUIRED,
                    6,
                    "8/8/8/8 or 16/16 syllables",
                    patterns=((8, 8, 8, 8), (16, 16)),
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Sanskrit quantity, caesurae, and metrical pathyā/vipulā rules are not modeled.",),
            assessment_mode="partial",
        ),
        fixed(
            "double_dactyl",
            "Double Dactyl",
            "comic fixed form",
            "Twentieth-century English light verse",
            "Two quatrains built chiefly from double-dactylic six-syllable lines, with shortened fourth and eighth lines that rhyme.",
            line_count=8,
            stanza_patterns=((4, 4), (8,)),
            syllables=(6, 6, 6, 4, 6, 6, 6, 4),
            extra_rules=(
                rule(
                    "rhyme",
                    "terminal_pair_rhyme",
                    "Short-line rhyme",
                    role.REQUIRED,
                    4,
                    "Lines 4 and 8 rhyme",
                    positions=(4, 8),
                ),
            ),
            meter=("dactylic", 2),
            source_urls=(POETRY_FOUNDATION_FORMS,),
            limitations=("The nonsense opening, proper name, and single six-syllable word convention require manual checking.",),
            assessment_mode="partial",
        ),
        fixed(
            "paradelle",
            "Paradelle",
            "nonce repetition form",
            "Contemporary English-language parody form",
            "A twenty-four-line poem in four sestets with prescribed repeated lines and word recombination.",
            line_count=24,
            stanza_patterns=((6, 6, 6, 6),),
            extra_rules=(
                rule(
                    "repetition",
                    "paradelle_repetition",
                    "Prescribed line repetition",
                    role.REQUIRED,
                    8,
                    "Lines 1/2 and 3/4 repeat in each of the first three sestets",
                ),
            ),
            source_urls=(wd + "poetic-form-paradelle",),
            limitations=("Exact word-inventory recombination is reported conservatively and punctuation is ignored.",),
        ),
        fixed(
            "kwansaba",
            "Kwansaba Structural Profile",
            "contemporary syllabic/word-count form",
            "African American / Eugene B. Redmond",
            "Seven lines of seven words each, conventionally limiting words to seven letters except proper nouns.",
            line_count=7,
            word_counts=(7, 7, 7, 7, 7, 7, 7),
            extra_rules=(
                rule(
                    "word_length",
                    "maximum_word_length",
                    "Seven-letter word limit",
                    role.PREFERRED,
                    4,
                    "Words contain no more than seven alphabetic characters, except proper nouns",
                    maximum=7,
                    exempt_proper_nouns=True,
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("The form's cultural and thematic relationship to Kwanzaa is not inferred.",),
            assessment_mode="partial",
        ),
        fixed(
            "sevenling",
            "Sevenling Structural Profile",
            "contemporary seven-line form",
            "Contemporary English-language",
            "Seven lines arranged as two tercets and a final line, with content-pattern requirements beyond structure.",
            line_count=7,
            stanza_patterns=((3, 3, 1), (7,)),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("The required lists, parallel subjects, and final-line relationship require manual confirmation.",),
            assessment_mode="manual",
        ),
        fixed(
            "collom_lune",
            "Collom Lune",
            "three-line short form",
            "Contemporary American",
            "A three-line lune containing three, five, and three words.",
            line_count=3,
            word_counts=(3, 5, 3),
            source_urls=(wd + "10-short-poetic-forms",),
        ),
        fixed(
            "kelly_lune",
            "Kelly Lune",
            "three-line short form",
            "Contemporary American",
            "A three-line lune containing five, three, and five syllables.",
            line_count=3,
            syllables=(5, 3, 5),
            source_urls=(wd + "10-short-poetic-forms",),
        ),
        fixed(
            "diamante",
            "Diamante Structural Profile",
            "seven-line word-count form",
            "Contemporary classroom form",
            "A seven-line diamond-shaped poem using a 1/2/3/4/3/2/1 word-count pattern.",
            line_count=7,
            word_counts=(1, 2, 3, 4, 3, 2, 1),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Part-of-speech and antonym/synonym semantic prescriptions are not automatically scored.",),
            assessment_mode="partial",
        ),
        fixed(
            "etheree",
            "Etheree",
            "syllabic staircase form",
            "Contemporary English-language",
            "A ten-line poem whose syllable counts rise from one to ten.",
            line_count=10,
            syllables=tuple(range(1, 11)),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "reverse_etheree",
            "Reverse Etheree",
            "syllabic staircase form",
            "Contemporary English-language",
            "A ten-line poem whose syllable counts descend from ten to one.",
            line_count=10,
            syllables=tuple(range(10, 0, -1)),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "double_etheree",
            "Double Etheree",
            "syllabic staircase form",
            "Contemporary English-language",
            "A twenty-line poem rising from one to ten syllables and descending from ten to one.",
            line_count=20,
            syllables=tuple(range(1, 11)) + tuple(range(10, 0, -1)),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "nonet",
            "Nonet",
            "syllabic staircase form",
            "Contemporary English-language",
            "A nine-line poem descending from nine syllables in line one to one syllable in line nine.",
            line_count=9,
            syllables=tuple(range(9, 0, -1)),
            source_urls=(wd + "nonet-poems-poetic-form",),
        ),
        fixed(
            "reverse_nonet",
            "Reverse Nonet",
            "syllabic staircase form",
            "Contemporary English-language",
            "A nine-line poem rising from one syllable in line one to nine syllables in line nine.",
            line_count=9,
            syllables=tuple(range(1, 10)),
            source_urls=(wd + "nonet-poems-poetic-form",),
        ),
        fixed(
            "fibonacci_poem",
            "Fibonacci / Fib Poem",
            "mathematical syllabic form",
            "Contemporary English-language",
            "A syllabic poem whose line lengths follow the Fibonacci sequence, commonly 1/1/2/3/5/8.",
            line_count=6,
            syllables=(1, 1, 2, 3, 5, 8),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "minute_poem",
            "Minute Poem",
            "syllabic rhyming form",
            "Contemporary English-language",
            "Three quatrains totaling sixty syllables, each stanza patterned 8/4/4/4 and rhyming AABB CCDD EEFF.",
            line_count=12,
            stanza_patterns=((4, 4, 4), (12,)),
            syllables=(8, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4),
            rhyme_schemes=("AABBCCDDEEFF",),
            source_urls=(wd + "minute-poem-poetic-forms",),
            limitations=("The alternating line lengths preclude one fixed whole-poem foot count; meter remains available in the separate meter analysis.",),
        ),
        fixed(
            "old_english_alliterative_verse",
            "Old English Alliterative Verse Profile",
            "accentual alliterative verse",
            "Old English / Germanic",
            "Long lines conventionally divided by a medial caesura, carrying four stresses and binding the half-lines through alliteration.",
            line_count=(2, 100000),
            extra_rules=(
                rule(
                    "stress",
                    "stress_count_range",
                    "Four-stress tendency",
                    role.PREFERRED,
                    4,
                    "Approximately four lexical stresses per line",
                    minimum=3,
                    maximum=5,
                ),
                rule(
                    "alliteration",
                    "alliteration_density",
                    "Alliterative binding",
                    role.REQUIRED,
                    6,
                    "Strong repeated initial-consonant evidence",
                    minimum=0.35,
                ),
            ),
            source_urls=(foundation + "old-english-poetry",),
            limitations=("Caesural half-line structure, Sievers types, morphology, and historical pronunciation are not modeled.",),
            assessment_mode="partial",
        ),
        fixed(
            "ottava_siciliana",
            "Ottava Siciliana",
            "Italian octave form",
            "Italian",
            "An eight-line hendecasyllabic stanza conventionally rhyming ABABABAB.",
            line_count=8,
            rhyme_schemes=("ABABABAB",),
            syllables=(11, 11, 11, 11, 11, 11, 11, 11),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Italian hendecasyllabic stress placement is not captured by English-oriented lexical stress.",),
        ),
        fixed(
            "strambotto",
            "Strambotto",
            "Italian octave form",
            "Italian",
            "An eight-line hendecasyllabic lyric, commonly rhyming ABABABAB or ABABABCC.",
            line_count=8,
            rhyme_schemes=("ABABABAB", "ABABABCC"),
            syllables=(11, 11, 11, 11, 11, 11, 11, 11),
            source_urls=(WRITERS_DIGEST_FORMS,),
            limitations=("Regional variants and Italian prosody require manual confirmation.",),
        ),
        fixed(
            "rispetto",
            "Rispetto",
            "Italian octave form",
            "Italian",
            "An eight-line poem of hendecasyllables, often a quatrain rhyming ABAB followed by two rhyming couplets, CCDD.",
            line_count=8,
            rhyme_schemes=("ABABCCDD",),
            syllables=(11, 11, 11, 11, 11, 11, 11, 11),
            source_urls=(wd + "10-short-poetic-forms",),
            limitations=("Italian prosody and regional variants require manual confirmation.",),
        ),
        fixed(
            "rondeau_redouble",
            "Rondeau Redoublé",
            "French fixed refrain form",
            "French and English",
            "Twenty-five lines: five quatrains and a closing quintet, with the first quatrain's lines returning successively as stanza closes.",
            line_count=25,
            stanza_patterns=((4, 4, 4, 4, 4, 5),),
            extra_rules=(
                rule(
                    "refrains",
                    "rondeau_redouble_refrains",
                    "Rotating refrain lines",
                    role.REQUIRED,
                    7,
                    "Opening quatrain lines close the next four quatrains",
                ),
            ),
            source_urls=(WRITERS_DIGEST_FORMS,),
        ),
        fixed(
            "chanso",
            "Chanso Structural Profile",
            "French stanza-and-envoi form",
            "French",
            "Five or six uniform stanzas followed by an envoi approximately half their length, with consistent syllable count and rhyme plan.",
            line_count=(12, 100000),
            extra_rules=(
                rule(
                    "architecture",
                    "chanso_architecture",
                    "Uniform stanzas and half-length envoi",
                    role.REQUIRED,
                    6,
                    "Five or six equal stanzas plus a half-length envoi",
                ),
                rule(
                    "uniformity",
                    "line_length_uniformity",
                    "Line-length regularity",
                    role.PREFERRED,
                    3,
                    "Consistent syllable count",
                ),
            ),
            source_urls=(wd + "chanso-poetic-form",),
            assessment_mode="partial",
        ),
        fixed(
            "haynaku",
            "Hay(na)ku",
            "three-line word-count form",
            "Contemporary Filipino diasporic / English-language",
            "A three-line poem containing one word, two words, and three words.",
            line_count=3,
            word_counts=(1, 2, 3),
            source_urls=(wd + "10-short-poetic-forms",),
        ),
        fixed(
            "shadorma",
            "Shadorma",
            "six-line syllabic form",
            "Contemporary form often described as Spanish-derived",
            "A six-line poem with a 3/5/3/3/7/5 syllable pattern.",
            line_count=6,
            syllables=(3, 5, 3, 3, 7, 5),
            source_urls=(wd + "10-short-poetic-forms",),
            limitations=("Claims about the form's Spanish historical origin are uncertain; the encoded syllabic convention is explicit.",),
        ),
        fixed(
            "magic_9",
            "Magic 9",
            "nine-line rhyme form",
            "Contemporary English-language",
            "A nine-line poem using the rhyme scheme ABACADABA.",
            line_count=9,
            rhyme_schemes=("ABACADABA",),
            source_urls=(wd + "10-short-poetic-forms",),
        ),
        fixed(
            "tricube",
            "Tricube",
            "mathematical syllabic form",
            "Contemporary English-language",
            "Three tercets of three-syllable lines: three by three by three.",
            line_count=9,
            stanza_patterns=((3, 3, 3),),
            syllables=(3, 3, 3, 3, 3, 3, 3, 3, 3),
            source_urls=(wd + "10-short-poetic-forms",),
        ),
        fixed(
            "generic_couplet_sequence",
            "Couplet Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into two-line stanzas.",
            line_count=(2, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Couplet sequence",
                    role.REQUIRED,
                    5,
                    "Two-line stanzas",
                    size=2,
                    minimum=1,
                ),
            ),
            source_urls=(POETS_GLOSSARY,),
            assessment_mode="manual",
            limitations=("A couplet is a stanza unit and does not by itself establish a more specific inherited form.",),
        ),
        fixed(
            "generic_tercet_sequence",
            "Tercet Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into three-line stanzas.",
            line_count=(3, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Tercet sequence",
                    role.REQUIRED,
                    5,
                    "Three-line stanzas",
                    size=3,
                    minimum=1,
                ),
            ),
            source_urls=(POETS_GLOSSARY,),
            assessment_mode="manual",
            limitations=("A tercet is a stanza unit and does not by itself establish a more specific inherited form.",),
        ),
        fixed(
            "generic_quatrain_sequence",
            "Quatrain Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into four-line stanzas.",
            line_count=(4, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Quatrain sequence",
                    role.REQUIRED,
                    5,
                    "Four-line stanzas",
                    size=4,
                    minimum=1,
                ),
            ),
            source_urls=(poets + "quatrain",),
            assessment_mode="manual",
            limitations=("A quatrain is a stanza unit and does not by itself establish a more specific inherited form.",),
        ),
        fixed(
            "generic_quintain_sequence",
            "Quintain / Cinquain Stanza Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into five-line stanzas.",
            line_count=(5, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Five-line stanza sequence",
                    role.REQUIRED,
                    5,
                    "Five-line stanzas",
                    size=5,
                    minimum=1,
                ),
            ),
            source_urls=(poets + "cinquain",),
            assessment_mode="manual",
        ),
        fixed(
            "generic_sestet_sequence",
            "Sestet Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into six-line stanzas.",
            line_count=(6, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Six-line stanza sequence",
                    role.REQUIRED,
                    5,
                    "Six-line stanzas",
                    size=6,
                    minimum=1,
                ),
            ),
            source_urls=(POETS_GLOSSARY,),
            assessment_mode="manual",
        ),
        fixed(
            "generic_septet_sequence",
            "Septet Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into seven-line stanzas.",
            line_count=(7, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Seven-line stanza sequence",
                    role.REQUIRED,
                    5,
                    "Seven-line stanzas",
                    size=7,
                    minimum=1,
                ),
            ),
            source_urls=(POETS_GLOSSARY,),
            assessment_mode="manual",
        ),
        fixed(
            "generic_octave_sequence",
            "Octave Sequence",
            "stanzaic structure",
            "Cross-cultural",
            "A poem organized predominantly into eight-line stanzas.",
            line_count=(8, 100000),
            extra_rules=(
                rule(
                    "stanzas",
                    "uniform_stanza_size",
                    "Eight-line stanza sequence",
                    role.REQUIRED,
                    5,
                    "Eight-line stanzas",
                    size=8,
                    minimum=1,
                ),
            ),
            source_urls=(POETS_GLOSSARY,),
            assessment_mode="manual",
        ),
    )

    manual_specs = (
        ("acrostic", "Acrostic", "letter-based form", "Cross-cultural", "A poem whose line initials spell a name, word, or message."),
        ("ae_freislighe", "Ae Freislighe", "Irish syllabic form", "Classical Irish", "A tightly regulated Irish quatrain involving seven-syllable lines, interlaced rhyme, and prescribed word endings."),
        ("aisling", "Aisling", "vision poem", "Irish-language", "A dream-vision poem in which Ireland appears personified, traditionally as a woman."),
        ("anagrammatic_poetry", "Anagrammatic Poetry", "letter-based form", "Contemporary and experimental", "A poem governed by the rearrangement of letters from a source word or phrase."),
        ("ars_poetica", "Ars Poetica", "metapoetic mode", "Cross-cultural", "A poem about poetry, poetics, or the act and role of writing poems."),
        ("aubade", "Aubade", "occasion/song form", "European lyric traditions", "A dawn song, often lamenting the parting of lovers at morning."),
        ("awdl_gywydd", "Awdl Gywydd", "Welsh strict-metre form", "Welsh-language", "A Welsh quatrain form governed by syllable count, end rhyme, internal rhyme, and cynghanedd."),
        ("barzeletta", "Barzeletta / Frottola-Barzelletta", "Italian refrain form", "Italian", "A musical Italian stanza-and-refrain form whose full rhyme and metrical conventions require edition-specific identification."),
        ("bhakti_poetry", "Bhakti Poetry", "devotional tradition", "South Asian", "Devotional poetry expressing love for or surrender to a deity within diverse South Asian traditions."),
        ("blackout_poem", "Blackout Poem", "found-text form", "Contemporary", "A poem created by obscuring most of a source text and retaining selected visible words."),
        ("blazon", "Blazon", "catalogue form", "European lyric traditions", "A poem cataloguing the physical attributes of a beloved or subject."),
        ("carol", "Carol", "song/refrain form", "Medieval and later European", "A song form commonly organized around a refrain or burden and stanzas."),
        ("cento", "Cento", "collage form", "Classical to contemporary", "A poem composed entirely from lines or passages taken from other works."),
        ("chanso_content", "Chanso / Canso Lyric Context", "courtly lyric genre", "Occitan and French", "A courtly lyric song whose stanzaic form, rhyme, and envoi vary by composition."),
        ("concrete_poetry", "Concrete / Shape Poetry", "visual form", "Modern and contemporary", "Poetry whose spatial typography and visual shape are integral to the work."),
        ("contrapuntal", "Contrapuntal Poem", "multi-path visual form", "Contemporary", "A poem arranged as multiple textual strands that can be read separately and together."),
        ("deibide", "Deibide", "Irish syllabic form", "Classical Irish", "An Irish quatrain form with strict syllabic, rhyme, stress, and consonance requirements."),
        ("dirge", "Dirge", "mourning song", "Cross-cultural", "A song or poem of grief commemorating the dead."),
        ("dramatic_monologue", "Dramatic Monologue", "persona form", "English and global traditions", "A poem spoken by a dramatic persona to an implied listener in a revealing situation."),
        ("eclogue", "Eclogue", "pastoral dialogue", "Classical and later European", "A short pastoral poem, traditionally structured as dialogue among shepherds."),
        ("ekphrasis", "Ekphrastic Poem", "responsive mode", "Classical to contemporary", "A poem that describes or responds to a visual artwork."),
        ("elegiac_couplet", "Elegiac Couplet", "classical quantitative form", "Ancient Greek and Latin", "A dactylic-hexameter line followed by a dactylic-pentameter line."),
        ("elegy", "Elegy", "mourning form", "Cross-cultural", "A poem expressing grief, sadness, loss, or memorial reflection."),
        ("elliptical_poetry", "Elliptical Poetry", "contemporary mode", "Contemporary American", "Poetry marked by obliquity, fragmentation, and withheld connective information."),
        ("epic", "Epic", "long narrative form", "Cross-cultural", "A long narrative poem recounting heroic or culture-defining actions."),
        ("epigram", "Epigram", "short witty form", "Classical to contemporary", "A brief, pointed poem or verse statement, often ending in wit or satire."),
        ("epistle", "Verse Epistle", "address form", "Classical to contemporary", "A poem written as a letter or direct address to an absent recipient."),
        ("epithalamion", "Epithalamion", "occasion poem", "Classical to contemporary", "A poem or song celebrating a marriage."),
        ("erasure", "Erasure Poem", "found-text form", "Contemporary", "A poem created by removing or obscuring language from an existing source text."),
        ("exquisite_corpse", "Exquisite Corpse", "collaborative generative form", "Surrealist and contemporary", "A collaboratively generated poem whose contributors ordinarily see only part of the developing work."),
        ("found_poem", "Found Poem", "appropriative/collage form", "Modern and contemporary", "A poem composed from language taken from non-poetic or prior source material."),
        ("free_verse", "Free Verse / Open Form", "open form", "Modern and contemporary", "Poetry not governed by a predetermined regular meter, rhyme scheme, or fixed stanza pattern."),
        ("ghinnawa", "Ghinnawa", "oral couplet tradition", "Bedouin / Egyptian", "A short oral lyric of two balanced lines whose cultural, musical, and linguistic requirements exceed English structural analysis."),
        ("glosa_variant", "Open Glosa / Glose Variant", "quotation-and-refrain form", "Spanish-derived", "A glosa variant that expands quoted lines as refrains without the strict 4-plus-40-line architecture."),
        ("gogyohka", "Gogyōka", "five-line short form", "Modern Japanese", "A five-line Japanese short form emphasizing one phrase per line without a fixed English syllable prescription."),
        ("golden_shovel", "Golden Shovel", "source-line end-word form", "Contemporary African American", "A poem whose successive end words reproduce, in order, the words of a line from another text."),
        ("haibun", "Haibun", "prose-and-verse hybrid", "Japanese and global", "A work combining prose with one or more haiku."),
        ("hymn", "Hymn", "devotional song", "Cross-cultural", "A lyric of devotion, reverence, or praise, often addressed to a deity or personified subject."),
        ("irregular_ode", "Irregular Ode", "ode type", "European and English-language", "An ode retaining elevated address while allowing variable stanzaic and metrical design."),
        ("lament", "Lament", "mourning form", "Cross-cultural", "A poem or song expressing grief, loss, or complaint."),
        ("lai", "Lai / Lay", "medieval narrative or lyric form", "French and Breton traditions", "A medieval narrative or lyric form with historically variable stanzaic and musical conventions."),
        ("list_poem", "List Poem", "catalogue form", "Cross-cultural", "A poem organized through an accumulating inventory of items, images, statements, or attributes."),
        ("litany", "Litany", "repetitive invocation form", "Religious and secular traditions", "A poem built from repeated invocations, responses, or supplications."),
        ("lyric_poetry", "Lyric Poem", "lyric mode", "Cross-cultural", "A non-narrative poem presenting a concentrated voice, perception, or emotional state."),
        ("mock_epic", "Mock Epic", "satiric narrative mode", "European and English-language", "A poem applying elevated epic conventions to a deliberately trivial or comic subject."),
        ("nature_poetry", "Nature Poem", "thematic mode", "Cross-cultural", "A poem centrally engaging with the nonhuman world, landscape, ecology, or natural processes."),
        ("nocturne", "Nocturne", "occasion/setting form", "European and global", "A poem centered on night, nocturnal atmosphere, or night-associated reflection."),
        ("nonsense_verse", "Nonsense Verse", "comic mode", "Cross-cultural", "Playful verse organized around absurdity, invented language, rhyme, or sound."),
        ("occasional_poem", "Occasional Poem", "occasion form", "Cross-cultural", "A poem written for, performed at, or responding to a particular public or private event."),
        ("ode", "Ode", "formal address", "Classical to contemporary", "A formal lyric address celebrating, contemplating, or invoking a person, object, event, or abstraction."),
        ("oriki", "Oríkì / Praise Poetry", "oral praise tradition", "Yorùbá", "Oral praise poetry invoking the attributes, histories, and lineages of a person, family, place, or deity."),
        ("organic_form", "Organic Form", "compositional principle", "Modern and contemporary", "A form understood as arising from the poem's particular content rather than a predetermined scheme."),
        ("pastoral", "Pastoral", "literary mode", "Classical to contemporary", "Poetry engaging idealized or contested rural life, landscape, labor, and nature."),
        ("persona_poem", "Persona Poem", "dramatic voice form", "Cross-cultural", "A poem spoken through an adopted historical, fictional, or otherwise distinct persona."),
        ("pindaric_ode", "Pindaric Ode", "ode type", "Ancient Greek and later adaptations", "An ode organized around strophe, matching antistrophe, and a differently structured epode."),
        ("political_poetry", "Political Poem", "thematic mode", "Cross-cultural", "Poetry engaging political events, systems, protest, activism, or collective power."),
        ("praise_poem", "Praise Poem", "tribute form", "Cross-cultural", "A poem of tribute, gratitude, celebration, or honor."),
        ("prose_poem", "Prose Poem", "prose-verse hybrid", "Modern and contemporary", "A poem presented without the line breaks conventionally associated with verse."),
        ("riddle", "Riddle Poem", "oral and literary short form", "Cross-cultural", "A poem that encodes a question, identity, or solution through figurative clues."),
        ("renku", "Renku", "linked collaborative form", "Japanese", "A collaborative linked-verse tradition developed from renga and governed by complex link-and-shift conventions."),
        ("saudade_poem", "Saudade Poem", "lyric mode", "Portuguese-language and diasporic", "A lyric organized around longing, absence, nostalgia, or an unattainable object."),
        ("slam_poetry", "Slam Poetry", "performance/competition form", "Contemporary", "Poetry composed for judged live performance within a poetry-slam context."),
        ("sonnet_sequence", "Sonnet Sequence", "linked sequence", "European and global", "A group of sonnets connected by subject, dramatic situation, persona, or narrative development."),
        ("sortha", "Sortha", "Hindi couplet form", "Hindi", "An inverted doha that transposes the doha's conventional 13/11 internal divisions."),
        ("spoken_word", "Spoken Word", "performance form", "Contemporary and oral traditions", "Poetry intended primarily for live performance and shaped by voice, timing, audience, and embodiment."),
        ("submerged_sonnet", "Submerged Sonnet", "embedded sonnet variant", "Modern and contemporary", "A fourteen-line sonnet structure embedded within a longer poem."),
        ("tan_renga", "Tan-Renga", "paired linked verse", "Japanese", "A short linked collaboration structurally resembling a 5/7/5 verse followed by a 7/7 response."),
        ("troubadour_canso", "Canso / Troubadour Song", "courtly lyric genre", "Occitan", "A strophic troubadour love song with repeated metrical and rhyme design specific to the composition."),
        ("ubi_sunt", "Ubi Sunt Poem", "elegiac motif/form", "Medieval and later traditions", "A poem organized by 'where are they?' questions concerning vanished people, times, or things."),
        ("verbless_poetry", "Verbless Poem", "grammatical constraint form", "Contemporary", "A poem written without verbs."),
        ("verse_novel", "Verse Novel", "book-length hybrid form", "Modern and contemporary", "A novel-length narrative told primarily through verse."),
        ("virelai", "Virelai", "French fixed song form", "Medieval French", "A medieval French formes-fixes song whose refrain, stanza, rhyme, and musical pattern require version-specific identification."),
        ("zappai", "Zappai", "Japanese short-form category", "Japanese", "A miscellaneous Japanese seventeen-sound form outside haiku's seasonal and cutting conventions."),
        ("zejel", "Zéjel / Zajal", "strophic song form", "Arabic-Andalusian and Spanish traditions", "A strophic song form with a rhyming refrain and stanzas returning to the refrain rhyme."),
        ("zuihitsu", "Zuihitsu", "prose-and-verse miscellany", "Japanese", "A discontinuous assemblage of prose, observations, lists, anecdotes, and poetry responding to experience."),
    )

    manual_profiles = tuple(
        manual(
            profile_id,
            name,
            family,
            tradition,
            definition,
            source_urls=(
                POETS_GLOSSARY
                if profile_id
                in {
                    "aisling",
                    "ars_poetica",
                    "aubade",
                    "bhakti_poetry",
                    "blazon",
                    "cento",
                    "concrete_poetry",
                    "contrapuntal",
                    "dirge",
                    "dramatic_monologue",
                    "eclogue",
                    "ekphrasis",
                    "elegy",
                    "elliptical_poetry",
                    "epic",
                    "epigram",
                    "epistle",
                    "erasure",
                    "exquisite_corpse",
                    "found_poem",
                    "free_verse",
                    "golden_shovel",
                    "haibun",
                    "hymn",
                    "lament",
                    "list_poem",
                    "litany",
                    "lyric_poetry",
                    "mock_epic",
                    "nature_poetry",
                    "nocturne",
                    "nonsense_verse",
                    "occasional_poem",
                    "ode",
                    "oriki",
                    "organic_form",
                    "pastoral",
                    "persona_poem",
                    "political_poetry",
                    "praise_poem",
                    "prose_poem",
                    "riddle",
                    "saudade_poem",
                    "sonnet_sequence",
                    "spoken_word",
                    "submerged_sonnet",
                    "verbless_poetry",
                    "verse_novel",
                    "zuihitsu",
                }
                else WRITERS_DIGEST_FORMS,
            ),
        )
        for profile_id, name, family, tradition, definition in manual_specs
    )
    return automatic + manual_profiles


__all__ = ["build_expanded_form_profiles"]
